### ISSUE TITLE
doesn't work in Mathematica 10

### ISSUE THREAD

**Issue by serg-bloim** [halirutan/MathematicaAutocompletionTweaker#2]

**Comment by halirutan** [comment]
Have you read the whole description in the [README](https://github.com/halirutan/MathematicaAutocompletionTweaker/blob/master/README.md)? In the end it links to a very detailed post on stackexchange. There, the very first preface paragraph goes:

> [Starting] with Mathematica version **9.0.1** the following answer not valid anymore because the underlying protocol between front end and kernel was changed. Fortunately, we started to implement an open-source Mathematica plugin for IntelliJIDEA which has a full support for camel-hump completion.

So yes, it doesn't work anymore and it will never do again in versions > 9.0 because Wolfram changed the protocol how the autocompletion is working and made it completely inaccessible.
